version: '2'

services:
    web:
        build: .
        restart: always
        ports:
            - "80:8080"
            - "465:465"
        volumes:
            - ./client/assets/images/teamLogo:/app/client/assets/teamLogo
        links:
            - mongo
        env_file: .env
        command: bash -c "node server"
    mongo:
        image: mongo
