web:
  build: .
  restart: always
#  ports:
#    - "80:8080"
#    - "465:465"
  links:
    - mongo
  env_file: .env
  command: bash -c "node server"

mongo:
  image: mongo
  volumes:
    - ./mongo_data:/data/db